### ISSUE TITLE
unexpected 22 empty columns in addition to 24 known columns

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/natural-history-museum-london-interactions-bank#2]
Previously, 24 columns were present in the output.csv of NHM Interaction Bank. According the recent travis check (see https://travis-ci.org/globalbioticinteractions/natural-history-museum-london-interactions-bank/builds/271807937, see log snip below), 46 columns are now present. At first glance, none of the new columns have headers or values. 

@edwbaker Are the new column additions expected? 

19:27:23,857  INFO ResourceUtil:39 - caching of [http://data.nhm.ac.uk/api/3/action/package_show?id=nhm-ib] complete.
19:27:23,916  INFO ResourceUtil:37 - caching of [http://data.nhm.ac.uk/dataset/82e807f0-6273-4f19-be0a-7f7558442a25/resource/9f49865f-ca81-488e-8738-82c569fb562e/download/output.csv] started...
19:28:34,576  INFO ResourceUtil:39 - caching of [http://data.nhm.ac.uk/dataset/82e807f0-6273-4f19-be0a-7f7558442a25/resource/9f49865f-ca81-488e-8738-82c569fb562e/download/output.csv] complete.
19:28:34,582 ERROR StudyImporterForGitHubData:63 - failed to import data from repo [globalbioticinteractions/natural-history-museum-london-interactions-bank]
org.eol.globi.data.StudyImporterException: read [46] columns, but found [24] column definitions.
	at org.eol.globi.data.StudyImporterForMetaTable.importAll(StudyImporterForMetaTable.java:267)
	at org.eol.globi.data.StudyImporterForMetaTable.importTable(StudyImporterForMetaTable.java:127)
	at org.eol.globi.data.StudyImporterForMetaTable.importStudy(StudyImporterForMetaTable.java:67)
	at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:86)
	at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:59)
	at org.eol.globi.tool.GitHubRepoCheck.main(GitHubRepoCheck.java:86)

**Comment by edwbaker** [comment]
Shouldn't be any different - any idea what line of the file the issue arises on?

**Comment by jhpoelen** [comment]
First line has a bunch of extra commas in it.

**Comment by edwbaker** [comment]
I have fixed some issues - it would be helpful to know what line it is failing on now, is that possible to get?

**Comment by edwbaker** [comment]
Managed to track them down. A number of other potential issues also fixed.

**Comment by jhpoelen** [comment]
@edwbaker glad to hear that the issues were fixed. And yes, line numbers would be nice to include in the report. I've opened a separate issue on that here: https://github.com/jhpoelen/eol-globi-data/issues/313 .
